// know.js

const lessonOneDayOneWeek = {
    // Неделя 1
    week1: {
      day1: {
        date: "2025-01-20", // Дата для первого дня
        lesson1: "ЧиО",
        lesson1hom: "",
        lesson2: "русский язык",
        lesson2hom: "",
        lesson3: "русский язык",
        lesson3hom: "",
        lesson4: "кыргызский язык",
        lesson4hom: "",
        lesson5: "математика",
        lesson5hom: "",
        lesson6: "технология",
        lesson6hom: "",
      },
      day2: {
        date: "2025-01-21",
        lesson1: "литература",
        lesson1hom: "",
        lesson2: "литература",
        lesson2hom: "",
        lesson3: "математика",
        lesson3hom: "",
        lesson4: "математика",
        lesson4hom: "",
        lesson5: "физкультура",
        lesson5hom: "",
        lesson6: "кыргызский язык",
        lesson6hom: "",
      },
      day3: {
        date: "2025-01-22",
        lesson1: "история",
        lesson1hom: "",
        lesson2: "английский язык",
        lesson2hom: "",
        lesson3: "кыргызская литература",
        lesson3hom: "",
        lesson4: "русский язык",
        lesson4hom: "",
        lesson5: "русский язык",
        lesson5hom: "",
        lesson6: "история",
        lesson6hom: "",
      },
      day4: {
        date: "2025-01-23",
        lesson1: "музыка",
        lesson1hom: "",
        lesson2: "математика",
        lesson2hom: "",
        lesson3: "английский язык",
        lesson3hom: "",
        lesson4: "биология",
        lesson4hom: "",
        lesson5: "биология",
        lesson5hom: "",
        lesson6: "физкультура",
        lesson6hom: "",
      },
      day5: {
        date: "2025-01-24",
        lesson1: "география",
        lesson1hom: "",
        lesson2: "ОИВТ",
        lesson2hom: "",
        lesson3: "английский язык",
        lesson3hom: "",
        lesson4: "ИХТ",
        lesson4hom: "",
        lesson5: "география",
        lesson5hom: "",
        lesson6: "классный час",
        lesson6hom: "",
      },
      day6: {
        date: "2025-01-25",
        lesson1: "суббота",
        lesson1hom: "отдых",
        lesson2: "суббота",
        lesson2hom: "отдых",
        lesson3: "суббота",
        lesson3hom: "отдых",
        lesson4: "суббота",
        lesson4hom: "отдых",
        lesson5: "суббота",
        lesson5hom: "отдых",
        lesson6: "суббота",
        lesson6hom: "отдых",
      },
    },
  
    // Неделя 2
    week2: {
      day1: {
        date: "2025-01-27", // Дата для первого дня второй недели
        lesson1: "ЧиО",
        lesson1hom: "",
        lesson2: "русский язык",
        lesson2hom: "",
        lesson3: "русский язык",
        lesson3hom: "",
        lesson4: "кыргызский язык",
        lesson4hom: "",
        lesson5: "математика",
        lesson5hom: "",
        lesson6: "технология",
        lesson6hom: "",
      },
      day2: {
        date: "2025-01-28",
        lesson1: "литература",
        lesson1hom: "",
        lesson2: "литература",
        lesson2hom: "",
        lesson3: "математика",
        lesson3hom: "",
        lesson4: "математика",
        lesson4hom: "",
        lesson5: "физкультура",
        lesson5hom: "",
        lesson6: "кыргызский язык",
        lesson6hom: "",
      },
      day3: {
        date: "2025-01-29",
        lesson1: "история",
        lesson1hom: "",
        lesson2: "английский язык",
        lesson2hom: "",
        lesson3: "кыргызская литература",
        lesson3hom: "",
        lesson4: "русский язык",
        lesson4hom: "",
        lesson5: "русский язык",
        lesson5hom: "",
        lesson6: "история",
        lesson6hom: "",
      },
      day4: {
        date: "2025-01-30",
        lesson1: "музыка",
        lesson1hom: "",
        lesson2: "математика",
        lesson2hom: "",
        lesson3: "английский язык",
        lesson3hom: "",
        lesson4: "биология",
        lesson4hom: "",
        lesson5: "биология",
        lesson5hom: "",
        lesson6: "физкультура",
        lesson6hom: "",
      },
      day5: {
        date: "2025-01-31",
        lesson1: "география",
        lesson1hom: "",
        lesson2: "ОИВТ",
        lesson2hom: "",
        lesson3: "английский язык",
        lesson3hom: "",
        lesson4: "ИХТ",
        lesson4hom: "",
        lesson5: "география",
        lesson5hom: "",
        lesson6: "классный час",
        lesson6hom: "",
      },
      day6: {
        date: "2025-02-1",
        lesson1: "суббота",
        lesson1hom: "отдых",
        lesson2: "суббота",
        lesson2hom: "отдых",
        lesson3: "суббота",
        lesson3hom: "отдых",
        lesson4: "суббота",
        lesson4hom: "отдых",
        lesson5: "суббота",
        lesson5hom: "отдых",
        lesson6: "суббота",
        lesson6hom: "отдых",
      },
    },
  };
  